apiVersion: v1
kind: Service
metadata:
  name: slack-bot
  namespace: platform-ops
  labels:
    app: slack-bot
    app.kubernetes.io/name: slack-bot
    app.kubernetes.io/part-of: manyfold-platform
spec:
  selector:
    app: slack-bot
  ports:
    - port: 3000
      targetPort: http
      name: http
