apiVersion: v1
kind: ServiceAccount
metadata:
  name: slack-bot
  namespace: platform-ops
  labels:
    app: slack-bot
    app.kubernetes.io/name: slack-bot
    app.kubernetes.io/part-of: manyfold-platform
