import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier/flat'
import pluginVue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'
import vueParser from 'vue-eslint-parser'

export default [
  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,tsx,vue}']
  },
  {
    name: 'app/files-to-ignore',
    // test-results/ and playwright-report/ are generated by a failing Playwright
    // run and are full of traces and error contexts. Without them here, one
    // failed e2e run makes `pnpm lint` report thousands of errors in files
    // nobody wrote.
    ignores: [
      '**/dist/**',
      '**/dist-ssr/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/test-results/**',
      '**/playwright-report/**'
    ]
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser
      }
    }
  },
  // Last among the shared configs: turns off every rule that formats (Vue's included), so
  // Prettier alone owns layout and `pnpm lint` reports code problems only.
  prettierConfig,
  {
    languageOptions: {
      globals: {
        __APP_VERSION__: 'readonly',
        __BUILD_TIME__: 'readonly'
      }
    },
    rules: {
      'vue/multi-word-component-names': 'off',
      'no-useless-assignment': 'off'
    }
  }
]
