apiVersion: v1
kind: Service
metadata:
  name: website-backend
  namespace: website
  labels:
    app: website-backend
    app.kubernetes.io/name: website-backend
    app.kubernetes.io/part-of: manyfold-platform
spec:
  type: ClusterIP
  selector:
    app: website-backend
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
